os: linux
language: java
install: true
jdk: oraclejdk8
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then gradle htmlSanityCheck buildUnavailable ; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then gradle stageS3 --debug --stacktrace ; fi'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - secure: "k+Wu+DmqhFgk13vqk8ggpnAArKkLd2OgX9XEfWog/tuNFTXAJZXXCfnW7k38ePDl52hCiWV7VGernxWKr6bf7iCDN0enz1mXvsBDlYlCzwbL3fG7+WoQ6edxYkR+/ylLvk/n9JzUxvPWJ1yk2fO7giCgzyDpk5ny9fm7d1SbUaQ="
    - secure: "r7MVbhkiwGvHPg5R4I9x+0hOykhavMgp6MgTshI5fq4HMBNh9M5Yj5+FTeh6euGmMZGKnKBHkE7MT1Y7ZxJvK1L3AupovxHBI0094ZLmb2AZjOXsAujwJ46fOHSDN0nJCB7HrNg7JjO0hOlfZT6ogezANrBXGL5OPJrvhk+3ThU="
